<a href="https://colab.research.google.com/github/rizthafrrynthii/Tugas-Algoritma/blob/main/2208541042_Riztha_Ferryanthi_Maulinda_Tugas_V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pertemuan ke-5. Senin, 03 April 2023

## 5.16 ***List 2 Dimensi***

In [ ]:
matrik = [
[1,2,3,4], #baris dan kolom dimulai dari 0
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]]
print(matrik)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
matrik[0]

[1, 2, 3, 4]

In [ ]:
matrik[3][2]
#matrik dengan baris ke[3] dan kolom ke[2]

15

In [ ]:
import numpy as np       #np = numeric phyton
d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
for baris in matrik: #gunakan function for untuk mencetak matrik
  print(baris)
  for kolom in baris:
    print(kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


## 5.17 ***Tuples*** 

In [ ]:
#tuple sifatnya sensitif terhadap kelompoknya, sehingga isinya tidak dapat dirubah dan dimanipulasi

number = (1,2,3,4,5) #seperti biasa, inisialisasi terlebih dahulu
print(number)
print(number[0]) #index dimulai dari 0
print(number[0:3]) #jika ingin memanggil beberapa isi berurutan

number[0] #jika tidak menggunakan function print, maka programnya tidak akan berjalan
number[0]=2 
number.append(4)
number.remove(1)
#error karena tuple tidak dapat diganti, ditambah dan dikurangi

(1, 2, 3, 4, 5)
1
(1, 2, 3)


TypeError: ignored

In [ ]:
number.count(2) #selain index, kita juga bisa menggunakan count untuk memanggil anggota number

1

In [ ]:
number.index(4) #selain mennggunakan simbol [] untuk memanggil anggota, kita juga bisa menuliskan index()

3

## 5.18 ***Dictionaries***

In [ ]:
#Dictionaries digunakan jika datanya terkait satu sama lain

data_saya = {
    "nama" : "Riztha Ferryanthi Maulinda",
    "umur" : "20",
    "tempat_tinggal" : "Denpasar"
}

In [ ]:
print(data_saya["nama"])
print(data_saya.get["nama"]) #untuk mencari apakah terdapat "nama" di dalam data_saya

NameError: ignored

In [ ]:
data_saya["nomor_WA"] = '0897654321' #kita bisa menambahkan isi datanya juga
print(data_saya["nomor_WA"])

0897654321


In [ ]:
#latihan merubah angka menjadi sebutan bilangan tersebut

angka = {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan",
    "10": "sepuluh"
}

In [ ]:
nomor_WA = input("Masukan nomor WA mu : ")
nomor_angka = ""
for isi in nomor_WA :
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)   #jika dibuat menjorok, maka akan mencetak data seperti segitiga pascal                          

Masukan nomor WA mu : 081234567890
nol delapan satu dua tiga empat lima enam tujuh delapan sembilan nol 


## 5.19 **Fungsi dalam** ***Phyton***

In [ ]:
def full_name(first_name, last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [ ]:
first_name = input("nama depanmu adalah ")
last_name = input("nama belakangmu adalah ")
full_name(first_name,last_name)

nama depanmu adalah riztha
nama belakangmu adalah ferryanthi
Nama lengkapnya adalah riztha ferryanthi


## 5.19.1 **Tugas Fungsi pada** ***Phyton***

In [ ]:
def waktu_sampai(jarak,kecepatan): #yang diketahui
    waktu = jarak/kecepatan #rumus mencari waktu_sampai
    print(waktu)

In [ ]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [ ]:
waktu_sampai(50,5)

10.0


In [ ]:
waktu_tempuh(5,50)

0.1

In [ ]:
a = waktu_sampai(50,5)
print(a)

10.0
None


In [ ]:
b = waktu_tempuh(5,50)
print(b)

0.1


In [ ]:
#latihan membuat program untuk menghitung luas segitiga, lingkaran, persegi dan persegi panjang

import numpy as np

def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas

In [ ]:
jenis_bidang = input("Apa bidangnya? ")
if jenis_bidang.upper() == 'SEGITIGA':
   alas = float(input('Berapakah panjang alasnya? '))
   tinggi = float(input('Berapakah tingginya? '))
   luas = luas_segitiga(alas,tinggi)
   print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
     jari_jari = float(input('Berapakah panjang jari-jarinya? '))
     luas = luas_lingkaran(jari_jari)
     print(f"Luas {jenis_bidang} adalah {luas}")
elif (jenis_bidang.upper() == 'PERSEGI') or (jenis_bidang.upper() == 'BUJUR SANGKAR'):
     sisi = float(input('Berapakah panjang sisinya? '))
     luas = luas_persegi(sisi)
     print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
     panjang = float(input('Berapakah panjangnya? '))
     lebar = float(input('Berapakah lebarnya? '))
     luas = luas_persegi_panjang(panjang,lebar)
     print(f"Luas {jenis_bidang} adalah {luas}")
else:
     print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada")
     print("Pilihan hanya ada SEGITIGA, LINGKARAN  PERSEGI dan PERSEGI PANJANG.")
     print("Terimakasih")

## 5.20 **Numpy**

In [ ]:
#pertama-tama kita perlu memanggil numpy seperti berikut

import pandas as pd

5.20.1 **Perintah Dasar pada Numpy**

In [ ]:
#memanggil numpy

import numpy as np

a = np.array([0,1,2,3,4])
print(a)

b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

c = np.array([[[0,1,2,3],[4,5,6,7]],
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print(c)

[0 1 2 3 4]
[[5 6 7 8]
 [9 8 7 6]]
[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
#untuk mengetahui dimensinya gunakan perintah berikut

a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
c.ndim

3

In [ ]:
#lalu gunakan perintah dibawah ini untuk mengetahui ukuran variabelnya

a.shape

(5,)

In [ ]:
b.shape

(2, 4)

In [ ]:
c.shape

(3, 2, 4)

5.20.2 **Memanggil Anggota, Kolom dan Baris dengan Numpy**

In [ ]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #baris dimulai dari 0
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
d[0,3] #baris ke-0, kolom ke 3

4

In [ ]:
d[1,:] #memanggil baris ke-1 saja, : menandakan bahwa tidak memanggil kolom tertentu

array([5, 6, 7, 8])

In [ ]:
d[:,2] #memanggil kolom ke-2 saja dan mengabaikan barisnya

array([ 3,  7, 11])

In [ ]:
d[0,1:4] #memanggil baris ke-0, dengan kolom 1 sampai 4

array([2, 3, 4])

In [ ]:
d[0,0:4:1] #memanggil baris ke-0 dan kolom dari 0 sampai 4 dengan jarak 1

array([1, 2, 3, 4])

In [ ]:
#kita juga bisa mengubah angka dalam list dengan perintah seperti berikut

d[1,2] = 0 #ubah baris ke 1, kolom ke 2 dengan angka 0
print(d)

[[ 1  2  3  4]
 [ 5  6  0  8]
 [ 9 10 11 12]]


5.20.3 **Matrix pada Numpy**

In [ ]:
#kita bisa membuat berbagai jenis matrix dengan perintah numpy sebagai berikut

np.ones((2,3)) #perintah ini akan mencetak matrix angka 1 dengan 2 baris dan 3 kolom

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,2)) #matrix 0 dengan 3 baris dan 2 kolom

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.identity(4) #mencetak matrix identitas 4×4 atau bujur sangkar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.ones((2,3,4)) #mencetak 2 matrix dengan masing-masing matrix memiliki 3 baris dan 4 kolom

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full((3,2),9) #mencetak matrix 3 baris 2 kolom yang didalamnya penuh dengan angka 9

array([[9, 9],
       [9, 9],
       [9, 9]])

In [ ]:
np.random.rand(4,3) #mencetak matrix 4 baris 3 kolom dengan anggota bebas

array([[0.71792434, 0.76578412, 0.49615114],
       [0.07144967, 0.86508805, 0.30498294],
       [0.99544684, 0.06572361, 0.63620105],
       [0.0185739 , 0.82147985, 0.32757024]])

In [ ]:
np.random.randint(1,10,size=(3,4))

#perintah diatas digunakan untuk mencetak matrix berukuran 3×4 dengan anggota random mulai dari 1 sampai 10

array([[9, 4, 2, 9],
       [1, 4, 5, 3],
       [1, 2, 5, 1]])

5.20.4 ***Copy* pada Numpy**

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b = a
print(b)

[1 2 3 4 5]


In [ ]:
b[0] = 10
print(b)

[10  2  3  4  5]


In [ ]:
#setelah kode diatas dijalankan, kita akan kembali mencetak a

print(a)

#dari sini dapat dilihat outputnya berbeda dan malah mengikuti kode sebelumnya
#oleh karena itu dibutuhkan perintah copy untuk menghindari perubahan pada variabel awal

[10  2  3  4  5]


In [ ]:
#perhatikan contoh dibawah ini

import numpy as np

c = np.array([1,2,3,4,5])
print(c)

[1 2 3 4 5]


In [ ]:
d = c.copy()  #gunakan perintah copy
print(d)

[1 2 3 4 5]


In [ ]:
d[0] = 10
print(d)

[10  2  3  4  5]


In [ ]:
#lalu cetak c dan akan muncul variabel awalnya

print(c)

[1 2 3 4 5]


5.20.5 **Operasi Matematika pada *Numpy***

In [ ]:
a+2 #penjumlahan
a-2 #pengurangan
a*2 #perkalian
a/2 #pembagian
a**2 #perpangkatan

In [ ]:
import numpy as np

b = np.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


In [ ]:
a+b
a-b
a*b
a/b
b**a

array([60466176,       49,      512,     6561,   100000])

In [ ]:
np.sin(a)
np.cos(a)
np.tan(a)

array([ 0.64836083, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [ ]:
np.sinh(a)
np.cosh(a)
np.tanh(a)
np.sqrt(a)

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798])

5.20.6 **Perkalian Matrix pada *Numpy***

In [ ]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b = np.array([[9,10,11,12],[13,14,15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
c = a*b  #mengalikan matriks a dan b
print(c)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [ ]:
d = np.matmul(a,b) #error karena tidak menggunakan perintah print

ValueError: ignored

In [ ]:
e =np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
f = np.matmul(a,e)
print(f)

[[130 140]
 [322 348]]


In [40]:
g = a*e

5.20.7 **min, max dan sum pada *Numpy***

In [ ]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b = np.min(a)  #mencari nilai minimum dari a
print(b)

1


In [ ]:
c = np.min(a,axis=0) 
print(c)

[1 2 3 4]


In [ ]:
d = np.min(a,axis=1)
print(d)

[1 5 9]


In [43]:
e = np.max(a)  #mencari nilai maksimum dari a
print(e)

12


In [44]:
f = np.max (a,axis=0)
print(f)

[ 9 10 11 12]


In [45]:
g = np.max(a,axis=1)
print(g)

[ 4  8 12]


In [46]:
h = np.sum(a)
print(h)

78


In [47]:
h = np.sum(a,axis=0)
print(h)

[15 18 21 24]


In [48]:
i = np.sum(a,axis=1)
print(i)

[10 26 42]
